# Local application.yml file

server:
  port: 8088
  servlet:
    context-path: /api/v1/

springdoc:
  default-produces-media-type: application/json

spring:
  servlet:
    multipart:
      max-file-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: dev
    password: dev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: dev
    password: dev
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 7e9778b3562564d23f3c5937c32a9b178c386c34842a564332d7e193cea2a71a
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      photos-output-path: ./uploads
  frontend:
    http:
      url: http://localhost:4200