spring:
  datasource:
    url: ${POSTGRESQL_DB_URL}
    username: ${POSTGRESQL_DB_USERNAME}
    password: ${POSTGRESQL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${EMAIL_HOST_NAME}
    port: 465
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true
    protocol: smtp

application:
  security:
    jwt:
      secret-key: 7e9778b3562564d23f3c5937c32a9b178c386c34842a564332d7e193cea2a71a
      expiration: 86400000
  mailing:
    frontend:
      activation-url: ${frontend.host}/activate-account
  file:
    upload:
      photos-output-path: ./uploads

server:
  port: 8088

frontend:
  host: ${FRONT_END_HOST}