/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {UserResponse} from './user-response';

export interface FeedbackResponse {
  comment?: string;
  note?: number;
  ownFeedback?: boolean;
  user?: UserResponse;
  createdDate?: string;
}
