name: CI / Keycloak

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-24.04
    name: Compile project
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Compile project
        run: |
          set -eu
          cd platform/iam/keycloak-spi

          echo "Starting compilation..."
          chmod +x mvnw
          ./mvnw clean compile
          echo "Compilation completed successfully"